provider:
  name:         faas
  gateway:      gateway.assembel.com

functions:
  assembel-ocr:
    lang:       Dockerfile
    handler:    ./openfaas-ocr
    image:      eu.gcr.io/radiant-pen-240113/openfaas-ocr:0.3.0
